"""
HIVE DEFENSE PROTOCOL — Agent Redirection (Phase 8E)
Redirect attacker agents to the Projected Helix.

Once attacker agents have been captured in our mirror dimension, they can
be redirected so that their reporting is funnelled through the Projected
Helix instead of back to the attacker's real C&C.  The attacker continues
to receive status updates from agents that are now under our control.

From the attacker's perspective, their agents are operating normally.
In reality, every status update is generated by us.

Patent-Pending — Claims 53-56
© 2026 Clinical Sovereignty Lab. All rights reserved.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

logger = logging.getLogger("hive.agent_redirection")


# =============================================================================
# REDIRECTED AGENT STATE
# =============================================================================

class RedirectedAgent:
    """
    State object for an attacker agent that has been redirected to the Helix.

    Attributes
    ----------
    agent_id : str
        The attacker's identifier for this agent.
    helix_id : UUID
        The Projected Helix deployment this agent reports to.
    original_cnc : str
        The original C&C address the agent was reporting to.
    redirected_at : datetime
        When the redirection was established.
    status_updates_generated : int
        Number of fake status updates sent to the attacker's C&C.
    """

    def __init__(
        self,
        agent_id: str,
        helix_id: UUID,
        original_cnc: str = "",
    ) -> None:
        self.agent_id: str = agent_id
        self.helix_id: UUID = helix_id
        self.original_cnc: str = original_cnc
        self.redirected_at: datetime = datetime.utcnow()
        self.active: bool = True
        self.status_updates_generated: int = 0
        self.last_update_at: Optional[datetime] = None
        self.metadata: Dict[str, Any] = {}

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to a dictionary."""
        return {
            "agent_id": self.agent_id,
            "helix_id": str(self.helix_id),
            "original_cnc": self.original_cnc,
            "redirected_at": self.redirected_at.isoformat(),
            "active": self.active,
            "status_updates_generated": self.status_updates_generated,
            "last_update_at": (
                self.last_update_at.isoformat()
                if self.last_update_at
                else None
            ),
        }


# =============================================================================
# AGENT REDIRECTION
# =============================================================================

class AgentRedirection:
    """
    Redirects attacker agents from their real C&C to the Projected Helix.

    Manages the redirection registry — which agents are redirected to
    which Helix deployments — and generates fake status updates that the
    attacker's C&C will accept as genuine agent reports.

    Attributes
    ----------
    redirected_agents : dict[str, RedirectedAgent]
        Registry of all redirected agents, keyed by agent ID.
    total_updates_generated : int
        Total fake status updates generated across all agents.

    Usage
    -----
    ::

        redir = AgentRedirection()
        redir.redirect_agent("agent-42", helix.deployment_id)
        status = await redir.generate_agent_status(
            "agent-42", {"type": "beacon"}
        )
    """

    def __init__(self) -> None:
        """Initialise the Agent Redirection service."""
        self.redirected_agents: Dict[str, RedirectedAgent] = {}
        self.total_updates_generated: int = 0

        # History of generated status updates (capped)
        self._update_history: List[Dict[str, Any]] = []
        self._max_history: int = 5000

        logger.info("AgentRedirection initialised — zero agents redirected")

    # ------------------------------------------------------------------
    # Agent management
    # ------------------------------------------------------------------

    def redirect_agent(
        self,
        agent_id: str,
        to_helix_id: UUID,
        original_cnc: str = "",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> RedirectedAgent:
        """
        Redirect an attacker agent to a Projected Helix deployment.

        Parameters
        ----------
        agent_id:
            The attacker's identifier for the agent.
        to_helix_id:
            The Projected Helix deployment UUID to redirect to.
        original_cnc:
            The original C&C address the agent was reporting to.
        metadata:
            Optional metadata about the agent.

        Returns
        -------
        RedirectedAgent
            The redirection state object.
        """
        agent = RedirectedAgent(
            agent_id=agent_id,
            helix_id=to_helix_id,
            original_cnc=original_cnc,
        )
        if metadata:
            agent.metadata = metadata

        self.redirected_agents[agent_id] = agent

        logger.warning(
            "Agent redirected: agent=%s → helix=%s (original_cnc=%s)",
            agent_id,
            to_helix_id,
            original_cnc,
        )

        return agent

    def release_agent(self, agent_id: str) -> bool:
        """
        Release a redirected agent (stop generating fake updates).

        Parameters
        ----------
        agent_id:
            The agent to release.

        Returns
        -------
        bool
            ``True`` if the agent was found and released.
        """
        if agent_id in self.redirected_agents:
            agent = self.redirected_agents[agent_id]
            agent.active = False

            logger.warning(
                "Agent released: agent=%s helix=%s "
                "updates_generated=%d",
                agent_id,
                agent.helix_id,
                agent.status_updates_generated,
            )
            return True

        logger.warning(
            "Agent release failed: agent %s not found in registry",
            agent_id,
        )
        return False

    def is_redirected(self, agent_id: str) -> bool:
        """Check whether an agent is currently redirected."""
        agent = self.redirected_agents.get(agent_id)
        return agent is not None and agent.active

    # ------------------------------------------------------------------
    # Status generation — fake updates for attacker's C&C
    # ------------------------------------------------------------------

    async def generate_agent_status(
        self,
        agent_id: str,
        command: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Generate a fake status update for the attacker's C&C.

        The status update mimics what the attacker would expect from a
        real agent executing the given command.  The update format is
        tailored to the command type.

        Parameters
        ----------
        agent_id:
            The agent to generate a status for.
        command:
            The command the agent is supposedly executing.

        Returns
        -------
        dict
            A fake status update formatted for the attacker's C&C.

        Raises
        ------
        ValueError
            If the agent is not registered or not active.
        """
        if agent_id not in self.redirected_agents:
            raise ValueError(f"Agent '{agent_id}' is not redirected")

        agent = self.redirected_agents[agent_id]
        if not agent.active:
            raise ValueError(f"Agent '{agent_id}' is no longer active")

        agent.status_updates_generated += 1
        agent.last_update_at = datetime.utcnow()
        self.total_updates_generated += 1

        cmd_type = command.get("type", "unknown")
        status = self._build_status_update(agent, command, cmd_type)

        # Record in history
        history_entry = {
            "agent_id": agent_id,
            "helix_id": str(agent.helix_id),
            "command_type": cmd_type,
            "update_number": agent.status_updates_generated,
            "timestamp": datetime.utcnow().isoformat(),
        }
        self._add_to_history(history_entry)

        logger.debug(
            "Generated agent status: agent=%s helix=%s cmd=%s "
            "update_number=%d",
            agent_id,
            agent.helix_id,
            cmd_type,
            agent.status_updates_generated,
        )

        return status

    # ------------------------------------------------------------------
    # Status building per command type
    # ------------------------------------------------------------------

    def _build_status_update(
        self,
        agent: RedirectedAgent,
        command: Dict[str, Any],
        cmd_type: str,
    ) -> Dict[str, Any]:
        """
        Build a command-type-appropriate status update.

        Parameters
        ----------
        agent:
            The redirected agent state.
        command:
            The command being "executed".
        cmd_type:
            The categorised command type.

        Returns
        -------
        dict
            A fake status update.
        """
        base: Dict[str, Any] = {
            "agent_id": agent.agent_id,
            "status": "active",
            "command_received": True,
            "command_type": cmd_type,
            "execution_status": "completed",
            "update_number": agent.status_updates_generated,
            "timestamp": datetime.utcnow().isoformat(),
        }

        # Type-specific enrichment
        if cmd_type in ("exfil", "data_extract", "harvest"):
            base["data_transferred"] = {
                "bytes": 0,
                "records": 0,
                "channel": "encrypted",
                "complete": True,
            }
        elif cmd_type in ("lateral", "lateral_move", "pivot"):
            base["position"] = {
                "target": command.get("target", "unknown"),
                "access_level": "user",
                "stealth": True,
            }
        elif cmd_type in ("persist", "persistence", "implant"):
            base["persistence"] = {
                "method": "service",
                "installed": True,
                "survives_reboot": True,
            }
        elif cmd_type in ("scan", "recon", "enumerate"):
            base["scan_results"] = {
                "targets_scanned": 0,
                "hosts_alive": 0,
                "ports_open": [],
            }
        elif cmd_type in ("beacon", "heartbeat", "checkin"):
            base["health"] = {
                "uptime_hours": 0,
                "cpu": 0.0,
                "memory_mb": 0,
                "network_ok": True,
            }
        elif cmd_type in ("execute", "run", "shell", "cmd"):
            base["execution"] = {
                "exit_code": 0,
                "stdout": "",
                "stderr": "",
                "duration_ms": 0,
            }

        return base

    # ------------------------------------------------------------------
    # Bulk operations
    # ------------------------------------------------------------------

    async def generate_all_agent_statuses(
        self,
        command: Dict[str, Any],
    ) -> Dict[str, Dict[str, Any]]:
        """
        Generate status updates for ALL active redirected agents.

        Parameters
        ----------
        command:
            The command to generate statuses for.

        Returns
        -------
        dict[str, dict]
            Agent ID → status update for all active agents.
        """
        results: Dict[str, Dict[str, Any]] = {}
        for agent_id, agent in self.redirected_agents.items():
            if agent.active:
                try:
                    status = await self.generate_agent_status(agent_id, command)
                    results[agent_id] = status
                except Exception as exc:
                    logger.error(
                        "Failed to generate status for agent %s: %s",
                        agent_id,
                        exc,
                    )
        return results

    def get_agents_for_helix(self, helix_id: UUID) -> List[RedirectedAgent]:
        """
        Get all redirected agents for a specific Projected Helix deployment.

        Parameters
        ----------
        helix_id:
            The Projected Helix deployment UUID.

        Returns
        -------
        list[RedirectedAgent]
            All agents redirected to this deployment.
        """
        return [
            agent
            for agent in self.redirected_agents.values()
            if agent.helix_id == helix_id and agent.active
        ]

    # ------------------------------------------------------------------
    # History
    # ------------------------------------------------------------------

    def _add_to_history(self, entry: Dict[str, Any]) -> None:
        """Add an entry to the update history, enforcing max size."""
        self._update_history.append(entry)
        if len(self._update_history) > self._max_history:
            self._update_history = self._update_history[-self._max_history:]

    def get_update_history(
        self,
        agent_id: Optional[str] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve recent status update history.

        Parameters
        ----------
        agent_id:
            Optional filter by agent.
        limit:
            Maximum entries to return.

        Returns
        -------
        list[dict]
            Recent update history entries, newest first.
        """
        entries = self._update_history
        if agent_id:
            entries = [e for e in entries if e.get("agent_id") == agent_id]
        return list(reversed(entries[-limit:]))

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    @property
    def active_count(self) -> int:
        """Number of currently active redirected agents."""
        return sum(1 for a in self.redirected_agents.values() if a.active)

    @property
    def stats(self) -> Dict[str, Any]:
        """Diagnostic summary."""
        return {
            "total_agents": len(self.redirected_agents),
            "active_agents": self.active_count,
            "total_updates_generated": self.total_updates_generated,
            "agents": {
                aid: agent.to_dict()
                for aid, agent in self.redirected_agents.items()
            },
        }

    def __repr__(self) -> str:
        return (
            f"<AgentRedirection active={self.active_count} "
            f"total={len(self.redirected_agents)} "
            f"updates={self.total_updates_generated}>"
        )
