"""
SOVEREIGN SWARM — Foresight Models
Emotional climate prediction and pattern activation data contracts (Patent Claims 9, 23).

Layer 6: Foresight — The System Sees Ahead.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# =============================================================================
# ENUMERATIONS
# =============================================================================

class ForesightStreamType(str, Enum):
    """The four input streams for the Foresight Engine."""
    INTERNAL_THERAPEUTIC = "internal_therapeutic"
    EXTERNAL_CULTURAL = "external_cultural"
    HISTORICAL_PATTERN = "historical_pattern"
    CONTEXTUAL_SIGNAL = "contextual_signal"


class ForesightScale(str, Enum):
    """Scales at which foresight predictions operate."""
    INDIVIDUAL = "individual"
    FAMILY = "family"
    COMMUNITY = "community"
    CULTURAL = "cultural"
    GLOBAL = "global"


class AlertSeverity(str, Enum):
    """Severity levels for foresight alerts."""
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


# =============================================================================
# FORESIGHT STREAM — Individual data stream input
# =============================================================================

class ForesightStream(BaseModel):
    """
    A single data stream feeding the Foresight Engine.
    The engine synthesizes all four stream types into predictions.
    """
    stream_id: UUID = Field(default_factory=uuid4)
    stream_type: ForesightStreamType
    source: str = Field(..., description="Source service or platform name")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    data: Dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    time_horizon_hours: Optional[float] = None
    scale: Optional[ForesightScale] = None
    cultural_context: Optional[str] = None


# =============================================================================
# FORESIGHT ALERT — Prediction output
# =============================================================================

class ForesightAlert(BaseModel):
    """
    A prediction generated by the Foresight Engine from multi-stream synthesis.
    Contains probabilistic forecasts of emotional climate shifts.
    """
    alert_id: UUID = Field(default_factory=uuid4)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    scale: ForesightScale = ForesightScale.INDIVIDUAL
    severity: AlertSeverity = AlertSeverity.MODERATE

    # Prediction
    signal_description: str = Field(..., description="What is being predicted")
    confidence_level: float = Field(..., ge=0.0, le=1.0)
    time_horizon_hours: float = Field(default=6.0)
    affected_populations: List[str] = Field(default_factory=list)

    # Source streams
    contributing_streams: List[ForesightStreamType] = Field(default_factory=list)
    supporting_data: Dict[str, Any] = Field(default_factory=dict)

    # Recommendations
    recommended_actions: List[str] = Field(default_factory=list)
    alternative_scenarios: List[Dict[str, Any]] = Field(default_factory=list)
    monitoring_indicators: List[str] = Field(default_factory=list)

    # Tracking
    outcome_verified: Optional[bool] = None
    accuracy_score: Optional[float] = None
    verified_at: Optional[datetime] = None


# =============================================================================
# PATTERN ACTIVATION — Transgenerational pattern alert
# =============================================================================

class PatternActivation(BaseModel):
    """
    Alert generated when a client's life circumstances match known
    trigger conditions for inherited emotional pattern activation.
    Patent Claim 23: Predictive Pattern Activation Alerts.
    """
    activation_id: UUID = Field(default_factory=uuid4)
    detected_at: datetime = Field(default_factory=datetime.utcnow)

    # Client context
    client_id: Optional[UUID] = None
    family_id: Optional[UUID] = None

    # Pattern details
    pattern_name: str = Field(..., description="Name of the transgenerational pattern")
    pattern_description: str = ""
    inherited_from: Optional[str] = Field(None, description="Generation source (e.g., 'maternal grandmother')")
    transmission_rate: float = Field(default=0.0, ge=0.0, le=1.0)

    # Trigger
    trigger_circumstances: List[str] = Field(default_factory=list)
    trigger_match_score: float = Field(default=0.0, ge=0.0, le=1.0)
    typical_manifestation_timeline_days: Optional[int] = None

    # Recommendations
    therapeutic_preparations: List[str] = Field(default_factory=list)
    recommended_modalities: List[str] = Field(default_factory=list)

    # Tracking
    alert_sent_to_team: bool = False
    outcome_tracked: bool = False
    actual_activation: Optional[bool] = None
    prediction_accuracy: Optional[float] = None
