#!/usr/bin/env python3
"""R5: regenerate frozen-config/ln7_droplet_requirements.lock.

Ops-invoked, not part of the runtime import graph or CI. Downloads pinned wheels
for a target platform/python via `pip download`, hashes them with `pip hash`, and
writes a --require-hashes-compatible lockfile.

Usage:
    python3 backend/scripts/ln7_generate_droplet_lockfile.py \
        --requirement certifi==2024.8.30 --requirement requests==2.32.3 \
        --platform manylinux2014_x86_64 --python-version 311 \
        --mirror-url https://pip.sovereignsanctuary.net/simple/ \
        --out frozen-config/ln7_droplet_requirements.lock

After regenerating, you MUST also regenerate frozen-config/manifest.sha256.json
(see backend/app/services/ln7_frozen_config.compute_manifest) or the fence check
will flag this file as an unpinned drift.

# QUANTUM-CRYSTAL-ARCH
"""
from __future__ import annotations

import argparse
import datetime
import subprocess
import sys
import tempfile
from pathlib import Path


def _download_and_hash(
    requirements: list[str],
    *,
    platform: str,
    python_version: str,
    implementation: str,
) -> dict[str, list[str]]:
    """Return {requirement: [pip-hash-format lines]} for each pinned requirement."""
    out: dict[str, list[str]] = {}
    with tempfile.TemporaryDirectory() as tmp:
        cmd = [
            sys.executable, "-m", "pip", "download",
            "--only-binary=:all:",
            "--platform", platform,
            "--python-version", python_version,
            "--implementation", implementation,
            "--abi", f"{implementation}{python_version}",
            "--no-deps",
            "-d", tmp,
            *requirements,
        ]
        subprocess.run(cmd, check=True)
        for whl in sorted(Path(tmp).glob("*")):
            hash_out = subprocess.run(
                [sys.executable, "-m", "pip", "hash", str(whl)],
                check=True, capture_output=True, text=True,
            ).stdout
            hash_line = next(
                (l.strip() for l in hash_out.splitlines() if l.strip().startswith("--hash=")),
                None,
            )
            if not hash_line:
                raise RuntimeError(f"pip hash produced no --hash line for {whl}")
            # Map back to the requirement by wheel filename prefix (normalize - -> _).
            name = whl.name.split("-")[0].replace("_", "-").lower()
            for req in requirements:
                req_name = req.split("==")[0].replace("_", "-").lower()
                if req_name == name:
                    out.setdefault(req, []).append(hash_line)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--requirement", "-r", action="append", required=True,
                     help="pinned requirement, e.g. requests==2.32.3 (repeatable)")
    ap.add_argument("--platform", default="manylinux2014_x86_64")
    ap.add_argument("--python-version", default="311")
    ap.add_argument("--implementation", default="cp")
    ap.add_argument("--mirror-url", required=True,
                     help="internal mirror index-url declared in the lockfile header")
    ap.add_argument("--out", default="frozen-config/ln7_droplet_requirements.lock")
    args = ap.parse_args()

    hashes = _download_and_hash(
        args.requirement,
        platform=args.platform,
        python_version=args.python_version,
        implementation=args.implementation,
    )

    missing = [r for r in args.requirement if r not in hashes]
    if missing:
        print(f"ERROR: no wheel resolved for: {missing}", file=sys.stderr)
        return 1

    lines = [
        "# R5 — frozen droplet bootstrap lockfile (regenerated by "
        "ln7_generate_droplet_lockfile.py).",
        "#",
        "# Hash-pinned per PEP 665 / pip --require-hashes convention. Every requirement",
        "# line below MUST carry at least one --hash=sha256:... — verified by",
        "# backend/app/services/ln7_droplet_lockfile.verify_droplet_lockfile().",
        "#",
        f"# internal-mirror-index-url: {args.mirror_url}",
        "# generated-by: backend/scripts/ln7_generate_droplet_lockfile.py",
        f"# generated-at: {datetime.datetime.now(datetime.timezone.utc).isoformat()}",
        f"# target: {args.platform} / {args.implementation}{args.python_version} / "
        f"{args.implementation}{args.python_version}",
        "",
    ]
    for req in sorted(args.requirement, key=str.lower):
        lines.append(f"{req} \\")
        for h in hashes[req]:
            lines.append(f"    {h}")
        lines.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines).rstrip("\n") + "\n")
    print(f"wrote {out_path} ({len(args.requirement)} requirements)")
    print("NOTE: now regenerate frozen-config/manifest.sha256.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
