-- 295_ln7_mutation_packs.sql
-- QUANTUM-CRYSTAL-ARCH — seed auto-generated mutation packs (G5 fix)
-- Additive only. Grows ln7_tasks past 300 with source='mutation'.
-- Generated by backend/scripts/ln7_generate_mutation_packs.py — every
-- pack below was self-verified: broken tree fails pytest, golden.patch
-- applied via the real runtime unified-diff applier makes it pass.

INSERT INTO ln7_tasks (
    task_id, source, difficulty, task_hash, split, pack_name,
    spdx_license, prompt_summary, metadata_json
)
VALUES
    (
        'pack:mut_off_by_one_range',
        'mutation',
        'easy',
        'f59a32bcbd3c16048a38f88b749cc039044bf5675661f31f693c0cab10e93373',
        'heldout',
        'mut_off_by_one_range',
        'FIRST-PARTY',
        'Fix off-by-one in cumulative sum',
        '{"pack": "mut_off_by_one_range", "gold_files": ["broken/ranges.py"]}'::jsonb
    ),
    (
        'pack:mut_and_or_swap',
        'mutation',
        'easy',
        'c3aba476e9eb7e04557948c011bca76018c296952965a24eb604aef1f3c5fe06',
        'train',
        'mut_and_or_swap',
        'FIRST-PARTY',
        'Fix boolean operator swap (and/or)',
        '{"pack": "mut_and_or_swap", "gold_files": ["broken/validators.py"]}'::jsonb
    ),
    (
        'pack:mut_wrong_index',
        'mutation',
        'easy',
        '27e97e7f72157cdf27630cb2d56278728cbd3d93f589fb5841efabefb0aed0a7',
        'train',
        'mut_wrong_index',
        'FIRST-PARTY',
        'Fix wrong index for last element',
        '{"pack": "mut_wrong_index", "gold_files": ["broken/lists.py"]}'::jsonb
    ),
    (
        'pack:mut_integer_division',
        'mutation',
        'easy',
        '2fc149f6e675ba8ed0eb01d38562dbb4cd20b3d42cbfd73358ccf2d317019722',
        'train',
        'mut_integer_division',
        'FIRST-PARTY',
        'Fix accidental integer division in average',
        '{"pack": "mut_integer_division", "gold_files": ["broken/stats.py"]}'::jsonb
    ),
    (
        'pack:mut_mutable_default_arg',
        'mutation',
        'easy',
        '78f8756525faf81d7981d7d3339eb4c5a7fe2c97f5462f45707515a2ed43e96d',
        'heldout',
        'mut_mutable_default_arg',
        'FIRST-PARTY',
        'Fix classic mutable default argument bug',
        '{"pack": "mut_mutable_default_arg", "gold_files": ["broken/collector.py"]}'::jsonb
    ),
    (
        'pack:mut_dict_get_default',
        'mutation',
        'easy',
        '84abffe9c0a70c92b99c2240dd0606acf04be79b0da09b37b3049dc5466105eb',
        'train',
        'mut_dict_get_default',
        'FIRST-PARTY',
        'Fix KeyError from direct dict indexing',
        '{"pack": "mut_dict_get_default", "gold_files": ["broken/config.py"]}'::jsonb
    ),
    (
        'pack:mut_swapped_args',
        'mutation',
        'easy',
        '6f91d16591bc3a61096fa9ba39606a4612f6a8889b5cef8f0aaf4e9585547fd0',
        'train',
        'mut_swapped_args',
        'FIRST-PARTY',
        'Fix swapped operand order in subtraction',
        '{"pack": "mut_swapped_args", "gold_files": ["broken/arith.py"]}'::jsonb
    ),
    (
        'pack:mut_is_vs_equals',
        'mutation',
        'easy',
        '43b14272296b9512de1c2f021e6edd42839c9a8479102517040c2eb1161abb22',
        'train',
        'mut_is_vs_equals',
        'FIRST-PARTY',
        'Fix identity check misused for value equality',
        '{"pack": "mut_is_vs_equals", "gold_files": ["broken/checks.py"]}'::jsonb
    ),
    (
        'pack:mut_reversed_sort',
        'mutation',
        'easy',
        'cbb4ef23ab1e14d6284cc28de2cb0ff98d38331c064ad4228a387d328a34a4ad',
        'train',
        'mut_reversed_sort',
        'FIRST-PARTY',
        'Fix ascending sort used where descending was required',
        '{"pack": "mut_reversed_sort", "gold_files": ["broken/ranking.py"]}'::jsonb
    ),
    (
        'pack:mut_off_by_one_slice',
        'mutation',
        'easy',
        '578df81756b778850bc49eb4eace70344212ba8ba5004479fe24343bce6c82b8',
        'train',
        'mut_off_by_one_slice',
        'FIRST-PARTY',
        'Fix off-by-one slice bound dropping the middle element',
        '{"pack": "mut_off_by_one_slice", "gold_files": ["broken/splitter.py"]}'::jsonb
    ),
    (
        'pack:mut_wrong_exception_type',
        'mutation',
        'easy',
        '575746743196404c482c9598d66aa1c71648219f32ff8b28486511f650c1a319',
        'train',
        'mut_wrong_exception_type',
        'FIRST-PARTY',
        'Fix wrong exception type caught in safe division',
        '{"pack": "mut_wrong_exception_type", "gold_files": ["broken/safe_math.py"]}'::jsonb
    ),
    (
        'pack:mut_string_strip_missing',
        'mutation',
        'easy',
        '0248eba3d41e96146c132330cff945a1992276a16e2d3a7d6994733c20ac417f',
        'train',
        'mut_string_strip_missing',
        'FIRST-PARTY',
        'Fix missing strip() before normalizing a name',
        '{"pack": "mut_string_strip_missing", "gold_files": ["broken/names.py"]}'::jsonb
    ),
    (
        'pack:mut_any_vs_all',
        'mutation',
        'easy',
        '6042fb0b9ed1200177aa53cd24df7c2aae91657a5b1cb8acefd4d7de82389853',
        'train',
        'mut_any_vs_all',
        'FIRST-PARTY',
        'Fix any()/all() confusion in positivity check',
        '{"pack": "mut_any_vs_all", "gold_files": ["broken/quantifiers.py"]}'::jsonb
    ),
    (
        'pack:mut_wrong_default_return',
        'mutation',
        'easy',
        '17e38924f58b899237e0af1fd66b7c72c9a563175b5e05cf664fe70d9d7d3db4',
        'train',
        'mut_wrong_default_return',
        'FIRST-PARTY',
        'Fix wrong sentinel returned on failed search',
        '{"pack": "mut_wrong_default_return", "gold_files": ["broken/search.py"]}'::jsonb
    ),
    (
        'pack:mut_negated_condition',
        'mutation',
        'easy',
        'c624e22c1121d1a356874af4b553c98fc63aa2c3e10500c58ccf823327e950f2',
        'train',
        'mut_negated_condition',
        'FIRST-PARTY',
        'Fix inverted emptiness check',
        '{"pack": "mut_negated_condition", "gold_files": ["broken/empties.py"]}'::jsonb
    ),
    (
        'pack:mut_wrong_comparison_bound',
        'mutation',
        'easy',
        '6e4084e08797fd103f0618a01630102a50a90fc366b32a1af97a63376152ebe1',
        'train',
        'mut_wrong_comparison_bound',
        'FIRST-PARTY',
        'Fix off-by-one grade threshold (strict vs inclusive bound)',
        '{"pack": "mut_wrong_comparison_bound", "gold_files": ["broken/grader.py"]}'::jsonb
    )
ON CONFLICT (task_id) DO NOTHING;
