#!/usr/bin/env bash
# Install repo git hooks (pre-commit SQL lint + pre-push CI gate). Idempotent; --sync refreshes when stamp drifts.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$ROOT" ]; then
  echo "install_git_hooks: not inside a git repository" >&2
  exit 1
fi

HOOKS_DIR="$ROOT/.git/hooks"
STAMP_FILE="$HOOKS_DIR/.sovereign-ci-gate-stamp"
LINTER="$ROOT/scripts/pre_commit_sql_lint.py"
PRE_PUSH="$ROOT/scripts/ci_gate_pre_push.sh"
INSTALLER="$ROOT/scripts/install_git_hooks.sh"
SELF_CHECK="$ROOT/scripts/ci_gate_self_check.sh"
CI_SCRIPT="$ROOT/backend/scripts/run_ci_tests.sh"

compute_stamp() {
  {
    [ -f "$INSTALLER" ] && shasum -a 256 "$INSTALLER"
    [ -f "$PRE_PUSH" ] && shasum -a 256 "$PRE_PUSH"
    [ -f "$SELF_CHECK" ] && shasum -a 256 "$SELF_CHECK"
    [ -f "$CI_SCRIPT" ] && shasum -a 256 "$CI_SCRIPT"
    [ -f "$LINTER" ] && shasum -a 256 "$LINTER"
  } | shasum -a 256 | awk '{print $1}'
}

install_hooks() {
  mkdir -p "$HOOKS_DIR"

  if [ -f "$LINTER" ] && [ ! -x "$LINTER" ]; then
    chmod +x "$LINTER"
  fi
  if [ -f "$PRE_PUSH" ] && [ ! -x "$PRE_PUSH" ]; then
    chmod +x "$PRE_PUSH"
  fi
  if [ -f "$SELF_CHECK" ] && [ ! -x "$SELF_CHECK" ]; then
    chmod +x "$SELF_CHECK"
  fi

  cat > "$HOOKS_DIR/pre-commit" <<EOF
#!/bin/bash
# Auto-generated by scripts/install_git_hooks.sh — DO NOT EDIT
exec python3 "\$(git rev-parse --show-toplevel)/scripts/pre_commit_sql_lint.py"
EOF
  chmod +x "$HOOKS_DIR/pre-commit"

  cat > "$HOOKS_DIR/pre-push" <<EOF
#!/bin/bash
# Auto-generated by scripts/install_git_hooks.sh — DO NOT EDIT
exec bash "\$(git rev-parse --show-toplevel)/scripts/ci_gate_pre_push.sh"
EOF
  chmod +x "$HOOKS_DIR/pre-push"

  compute_stamp > "$STAMP_FILE"
}

MODE="${1:-install}"

case "$MODE" in
  --stamp)
    compute_stamp
    ;;
  --sync)
    WANT="$(compute_stamp)"
    HAVE=""
    if [ -f "$STAMP_FILE" ]; then
      HAVE="$(tr -d '[:space:]' < "$STAMP_FILE")"
    fi
    if [ "$WANT" != "$HAVE" ] || [ ! -x "$HOOKS_DIR/pre-push" ] || [ ! -x "$HOOKS_DIR/pre-commit" ]; then
      install_hooks
      echo "install_git_hooks: refreshed hooks (stamp $WANT)" >&2
    fi
    ;;
  install|"")
    install_hooks
    echo "Installed:"
    echo "  $HOOKS_DIR/pre-commit  (SQL column lint)"
    echo "  $HOOKS_DIR/pre-push    (CI gate — run_ci_tests.sh)"
    echo "Stamp: $(tr -d '[:space:]' < "$STAMP_FILE")"
    echo "Test:  bash $ROOT/backend/scripts/run_ci_tests.sh"
    ;;
  *)
    echo "Usage: $0 [install|--sync|--stamp]" >&2
    exit 2
    ;;
esac
