#!/bin/bash
# Install scripts/pre_commit_sql_lint.py as a git pre-commit hook.
# Idempotent — safe to run multiple times.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK="$REPO_ROOT/.git/hooks/pre-commit"
LINTER="$REPO_ROOT/scripts/pre_commit_sql_lint.py"

if [ ! -x "$LINTER" ]; then
  chmod +x "$LINTER"
fi

cat > "$HOOK" <<'EOF'
#!/bin/bash
# Auto-generated by scripts/install_pre_commit_hook.sh — DO NOT EDIT
# Runs the narrow SQL column-name guard.
exec python3 "$(git rev-parse --show-toplevel)/scripts/pre_commit_sql_lint.py"
EOF
chmod +x "$HOOK"

echo "Installed: $HOOK"
echo "Test:      python3 $LINTER --all"
